
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: mezzo_test
  username: postgres
  password: password
  pool: 5
  timeout: 5000
  encoding: utf8

production:
  adapter: postgresql
  database: mezzo_production
  username: postgres
  password: password
  pool: 5
  timeout: 5000
  encoding: utf8
